nama = input("STATE YOUR NAME: ")
print("="*80)
print()
print("<"*10,"Adventure of", nama, ">"*10)
print()
print("Welcome to the Adventure of", nama)
kelamin = input("Are you a Male / Female? [M/F]\n >>")
print()
print()
print("One day, A young adventurer named",nama)
print("spawned in a peacefull Village of Orion")
print(nama,"walked out of village and see a slime jumping around.")
print()
senjata = input("Picked up a... (Sword/Bow)\n >> ")
print("and attack the slime.")
print("the slime get sliced and died. Adventurer gain a level.")
print()
print(nama,"The Adventurer, then run towards a chest that glows from the inside")
pilihan = input("PICK ONE!\n[OPEN/WALK]\n>> ")
print()
print("The Adventurer Finds a Gold and brings it Home to tje Village.")
pilihan2 = input("as the adventure walks, he started to feel more and more tired.\nTake a [Break] / Keep [Walk]ing\n>> ")
print()
pilihan3 = input("Valdo Arrived at the village and see RTX 3090 Ti on sale\nWith the price of 1 gold\n[BUY] / [PASS]>> ")
print("Congratulation! you got your dream stuff!\nNow you can play game Forever!")
print()
print("And live Happily ever after :)")